version: "3.9"
services:
    backend:
        image: geolocatorback
        container_name: geolocatorback
        build:
            context: ./backend
        ports:
            - "8080:80"
    frontend:
        image: geolocatorfront
        container_name: geolocatorfront
        build:
            context: ./frontend
        ports:
            - "4200:80"
        depends_on:
            - backend
